name: cod_soft_alarm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  alarm: ^3.0.8
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  permission_handler: ^11.2.1
  simple_ripple_animation: ^0.0.9
  timezone: ^0.9.3
  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "assets/logo2.png"
  ios: "assets/logo2.png"
  adaptive_icon_foreground: "assets/logo2.png"


flutter:
  uses-material-design: true

  assets:
    - assets/logo1.png
    - assets/harang3.mp3
